name: Build Project

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
        
      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main
          prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'

  backend-build-and-test:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Build and Test
    strategy:
      matrix:
        apis: [
          { project: "Auth.API" }, 
          { project: "Alunos.API" }, 
          { project: "Cursos.API" }, 
          { project: "Pagamentos.API" }, 
          { project: "BFF" }
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: ./src/**/packages.lock.json

      - name: Restore
        run: 
          dotnet restore ./Coldmart.sln

      - name: Build
        run: 
          dotnet build --no-restore ./Coldmart.sln
      
      - name: Test
        run: 
          dotnet test --no-build --no-restore ./Coldmart.sln --logger trx --results-directory "TestResults"

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults

      - name: Publish ${{ matrix.apis.project }}
        run: dotnet publish ./src/Coldmart.${{ matrix.apis.project }}/Coldmart.${{ matrix.apis.project }}.csproj --no-restore --configuration Release --output ./Coldmart.${{ matrix.apis.project }}
      
      - name: Upload ${{ matrix.apis.name }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.apis.project }}
          path: ./Coldmart.${{ matrix.apis.project }}

  backend-lint:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: "main"
          VALIDATE_ALL_CODEBASE: "false"
          VALIDATE_YAML: "true"
          VALIDATE_CSHARP: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  dependency-checks:
    needs: versionamento
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          base-ref: main
          head-ref: main

  code-security-check:
    needs: versionamento
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    
    strategy:
      matrix:
        include:
          - name: Backend
            language: csharp
            build-mode: autobuild
    
    steps:
      - uses: actions/checkout@v4

      - uses: github/codeql-action/init@v3
        name: Initialize CodeQL - ${{ matrix.name }}
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - uses: github/codeql-action/analyze@v3
        name: Analyze CodeQL - ${{ matrix.name }}
        with:
          category: "/language:${{ matrix.language }}"
  
  build-docker-image:
    needs: [versionamento, backend-build-and-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apis: [
          { name: "auth", project: "Auth.API" }, 
          { name: "alunos", project: "Alunos.API" }, 
          { name: "cursos", project: "Cursos.API" }, 
          { name: "pagamentos", project: "Pagamentos.API" }, 
          { name: "bff", project: "BFF" }
        ]

    env:
      version: ${{ needs.versionamento.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: 
          merge-multiple: false

      - name: Build Docker Image ${{ matrix.apis.name }}
        run: |
          docker build -f ./src/Coldmart.${{ matrix.apis.project }}/Dockerfile -t ${{ vars.DOCKERHUB_ACCOUNTID }}/${{ matrix.apis.name }}:${{ env.version }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ vars.DOCKERHUB_ACCOUNTID }}/${{ matrix.apis.name }}:${{ env.version }} ${{ vars.DOCKERHUB_ACCOUNTID }}/${{ matrix.apis.name }}:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Docker Push
        run: docker push --all-tags ${{ vars.DOCKERHUB_ACCOUNTID }}/${{ matrix.apis.name }}
